data: 
  unprocessed_files: ../data/
  processed_files: ../data/processed_files/
preprocess:
  chunk_size: 5000
  overlap: 100
embedding:
  dims: 200
  embedding_model: text-embedding-3-small
rag:
  index: 'goodfellas-chunk'
  llm: gpt-4o
  k: 5
test_control_variable:
  do_not_delete: 
