data: 
  unprocessed_files: ./data/
  processed_files: ./data/processed_files/
preprocess:
  chunk_size: 5000
  overlap: 100
embedding:
  dims: 200
  embedding_model: text-embedding-3-small
rag:
  llm: gpt-3.5-turbo
  k: 5
  index_to_query: 'goodfellas-chunk'
test_control_variable:
  do_not_delete: 
