data:
  data_path: ./data/
llm:
  chat_model: gpt-3.5-turbo
  embedding_dimension: 5
  embedding_model: text-embedding-3-small
preprocess:
  chunk_overlap: 3
  chunk_size: 30
rag:
  index_name: goodfellas-chunk
  top_k: 2
