env-variables:
  - openai_api_key: 
  - elastic_url: https://localhost:9200
  - elastic_password: 
  - ca_cert: ./http_ca.crt
data: 
  unprocessed_files: ./data/
  processed_files: ./data/processed_files/
preprocess:
  chunk_size: 1000
  overlap: 100
embedding:
  dims: 200
  embedding_model: text-embedding-3-small
rag:
  llm: gpt-3.5-turbo
  k: 5
test_control_variable:
  do_not_delete: 
