data:
  processed_files: ../data/processed_files/
  unprocessed_files: ../data/
llm:
  chat_model: gpt-4o
  embedding_dimension: 200
  embedding_model: text-embedding-3-small
preprocess:
  chunk_overlap: 100
  chunk_size: 4000
rag:
  index_name: goodfellas-chunk
  top_k: 7
