data:
  data_path: ./data/
llm:
  chat_model: gpt-4o-mini
  embedding_dimension: 200
  embedding_model: text-embedding-3-small
preprocess:
  chunk_overlap: 10
  chunk_size: 2800
rag:
  index_name: completo
  top_k: 5
